
spring:
  r2dbc:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5432/bucket
    username: postgres
    password: Vaifery111

  application:
    name: Bucket


server:
  port: 7001



